// Nomes usados pelo automatismo. Altera apenas esta lista quando necessário.
export const AUTOMATION_NAMES = [
  'Renato Batista Carvalho',
  'Andreia Botelho',
  'Fernando Paulo Duarte Ferreira',
  'Nuno Miguel Da Costa Bogalho',
  'Luís Alberto Duarte Ferreira',
  'Pedro Gonçalo Paixão Costa',
  'David Miguel Nunes Pereira',
  'Ricardo Nuno Trindade Paiva Filipe',
  'Jaime Bragança Rodrigues Martins',
  'João Luis Martins da Cunha',
  'Filipe Gonçalo dos Santos Duarte',
  'José Carlos Silva Campos Rodrigues',
  'Gonçalo Rafael dos Santos Neves',
  'Ruben Filipe Antunes Rocha',
  'Hugo Rafael Simões Mendes',
  'Filipa Baptista Prata',
  'Diogo Frederico Sacramento Cunha',
  'José Carriço',
  'Gonçalo José Vilão Rosa',
  'George Alexandre Barbeiro Silva',
  'Nelson Duarte',
  'Diogo André Oliveira Simões Neves',
  'João Bernardo Neves',
  'Nuno Matias',
  'Micael dos Santos Batista Pereira',
  'Nuno Miguel Santos Tedim Macieira Guerra',
  'Pedro Rafael Lopes Tomás',
  'Gonçalo Rafael Alves Cancela',
  'Andre Filie Silva Marques',
  'Diogo Manuel Moreira Baptista Neves',
  'Diogo Luz',
  'João Santos',
  'Alexandre Rato',
  'Marco Tavares',
  'Ricardo Silva',
  'João Bernardo Ramos Dias',
  'David Miguel Dias Gouveia',
  'André Andrade',
  'Daniela Roseiro Simões',
  'Sofia Nunes',
  'Mariana Pereira',
  'Joana Feteira',
  'Ana Martinho',
  'Joana Mafalda Lopes Nogueira',
  'Mariana Pedro',
  'Jessica Meira Pedreiras',
  'Inês Caetano',
  'Beatriz Alexandra Gonçalves Dias',
  'Camila Marques',
  'Ivo Manuel Torres da Rocha Fernandes',
  'Diogo Miguel Duarte Torres',
  'Carlos Lopes',
  'José Pedro Laranjeira',
  'Ricardo Jorge Eufrásio da Silva',
  'Tiago Filipe Ferreira Queirós',
  'Daniel Oliveira De Jesus',
  'Fernando Jorge Nunes Cordeiro',
  'Cátia Alexandra Graça Tavares',
  'João Martins',
  'Fabio Monteiro',
];

export const AUTOMATION_EMAIL = 'nucleomarquesbom@gmail.com';
